### ISSUE TITLE
request battery current decimal value

### ISSUE THREAD

**Issue by tropeadonato** [gch1p/inverter-tools#10]
hello, I would like to ask you if it is possible to read the decimals of the charging and discharging current of the battery, as there is not a unique value in watts relating to the battery (charged and discharged) and of the solar production, to overcome this I am doing some calculations to get the missing values but without decimals the error is notable, many thanks

**Comment by gch1p** [comment]
Hi. Unfortunately no. This is a limitation of voltronic's p18 protocol. For some parameters, they provide decimals, but not for these. 
![image](https://github.com/gch1p/inverter-tools/assets/18737999/01bc8ace-597c-479a-88ea-a4ccf07373d8)
