### ISSUE TITLE
response is invalid: while parsing p18::response_type::RatedInformation: item 14 is expected to be 2 characters long, got 3 characters

### ISSUE THREAD

**Issue by TheBarnHome** [gch1p/inverter-tools#9]
Hello,
I can successfully use inverted with the http proxy, except one command curl http://xxx.xxx.xxx.xxx:8080/get-rated/
The response is :
`{"result":"error","message":"response is invalid: while parsing p18::response_type::RatedInformation: item 14 is expected to be 2 characters long, got 3 characters"}`
Looking at the code, it seems my inverter is returning the max ac charge current on 3 digit instead of 2. It's currently set at 30A.
Thanks for your work.

**Comment by gch1p** [comment]
Hi, thank you for the report. Should be fixed by 25fdaac582dfc1518b5a8edef2cd2d3c06f9f0d2.

**Comment by TheBarnHome** [comment]
Problem solved, great !
Thanks,
Tristan
